#!/bin/bash

REMOTE_PATH="root@bladeismyna.me:/var/www/personal-site/dropzone/${1}"

if [ $# -eq 0 ]
then
    echo 'usage: catch file_name'
else
    SCP_COMMAND="scp -r ${REMOTE_PATH} ."

    echo $SCP_COMMAND
    eval $SCP_COMMAND
fi
